DELETE FROM user_table;
DELETE FROM selection;
DELETE FROM match_table;
DELETE FROM confederation;
DELETE FROM match_type;
INSERT INTO `testranglist`.`user_table` (`id`, `active`, `administator`, `password`, `username`) VALUES ('1', 'true', 'true', '$2y$10$q8gkCDrKtmlGWU5d8iGSgOCanVjOszjh0/JIbHl8B873Xj8sySrXe', 'user_test');
INSERT INTO `testranglist`.`user_table` (`id`, `active`, `administator`, `password`, `username`) VALUES ('3', 'true', 'true', '$2y$10$mYcgDfks60EaWbIK5u43Nu2yKDj3VSnyJZQvPQZViUkZo/4zQe/yq', 'veljko');
INSERT INTO `testranglist`.`user_table` (`id`, `active`, `administator`, `password`, `username`) VALUES ('7', 'false', 'false', 'update_user', 'update_user');  
INSERT INTO `testranglist`.`user_table` (`id`, `active`, `administator`, `password`, `username`) VALUES ('6', 'false', 'false', 'delete_user', 'delete_user');  
INSERT INTO `testranglist`.`confederation` (`id`, `name`, `strenght`) VALUES ('1', 'EUROPE', '1');
INSERT INTO `testranglist`.`confederation` (`id`, `name`, `strenght`) VALUES ('2', 'SOUTHAMERICA', '1'); 
INSERT INTO `testranglist`.`confederation` (`id`, `name`, `strenght`) VALUES ('3', 'AFRICA', '0.86');  
INSERT INTO `testranglist`.`confederation` (`id`, `name`, `strenght`) VALUES ('4', 'ASIA', '0.86'); 
INSERT INTO `testranglist`.`confederation` (`id`, `name`, `strenght`) VALUES ('5', 'NORTHAMERICA', '0.84');  
INSERT INTO `testranglist`.`confederation` (`id`, `name`, `strenght`) VALUES ('6', 'OCEANIA', '0.84');    
INSERT INTO `testranglist`.`selection` (`id`, `active`, `name`, `points`, `rang`, `confederation_id`, `user_id`) VALUES ('1', 'true', 'Serbia', '100', '1', '1', '3');
INSERT INTO `testranglist`.`selection` (`id`, `active`, `name`, `points`, `rang`, `confederation_id`, `user_id`) VALUES ('3', 'true', 'Austria', '50', '2', '1', '3');    
INSERT INTO `testranglist`.`selection` (`id`, `active`, `name`, `points`, `rang`, `confederation_id`, `user_id`) VALUES ('4', 'true', 'update_selection', '0', '0', '1', '3');
INSERT INTO `testranglist`.`selection` (`id`, `active`, `name`, `points`, `rang`, `confederation_id`, `user_id`) VALUES ('5', 'true', 'delete_selection', '0', '0', '1', '3');
INSERT INTO `testranglist`.`selection` (`id`, `active`, `name`, `points`, `rang`, `confederation_id`, `user_id`) VALUES ('10', 'true', 'transaction_selection', '0', '0', '1', '3');
INSERT INTO `testranglist`.`selection` (`id`, `active`, `name`, `points`, `rang`, `confederation_id`, `user_id`) VALUES ('11', 'true', 'transaction_selection2', '0', '0', '1', '3');
INSERT INTO `testranglist`.`match_type` (`id`,`name`, `strenght`) VALUES ('1','WORLDCUP', '1'); 
INSERT INTO `testranglist`.`match_type` (`id`,`name`, `strenght`) VALUES ('2','CONFEDERATIONCUP', '0.8'); 
INSERT INTO `testranglist`.`match_type` (`id`,`name`, `strenght`) VALUES ('3','QUALIFIER', '0.6'); 
INSERT INTO `testranglist`.`match_type` (`id`, `name`, `strenght`) VALUES ('4', 'FRIENDLY', '0.5');
INSERT INTO `testranglist`.`match_table` (`id`, `away_goals`, `match_date`, `host_goals`, `match_away`, `match_host`, `match_type_id`, `user_id`) VALUES ('1', '1', '2021-01-01', '3', '3', '1', '3', '1');
INSERT INTO `testranglist`.`match_table` (`id`, `away_goals`, `match_date`, `host_goals`, `match_away`, `match_host`, `match_type_id`, `user_id`) VALUES ('6', '1', '2021-01-01', '3', '3', '1', '3', '1');
INSERT INTO `testranglist`.`match_table` (`id`, `away_goals`, `match_date`, `host_goals`, `match_away`, `match_host`, `match_type_id`, `user_id`) VALUES ('7', '1', '2021-01-01', '3', '11', '10', '1', '1');
INSERT INTO `testranglist`.`match_table` (`id`, `away_goals`, `match_date`, `host_goals`, `match_away`, `match_host`, `match_type_id`, `user_id`) VALUES ('8', '1', '2021-01-01', '3', '10', '11', '1', '1');